### ISSUE TITLE
Create option to read tag

### ISSUE THREAD

**Issue by BOverdevest** [athombv/com.athom.homeyscript#31] opened 2021-04-01 21:45 UTC
From HomeScript it is possible to write a tag using
await tag("Tag Name for number", 1)  

it would be helpful if it would be possible to read a tag value again within the script.
maybe using
a = await tag("Tag Name for number")
which would then result in a being equal to 1

**Comment by jeroenwienk** [comment] 2021-04-02 15:27
It's possible with the API but it's not a very clear solution since the values are cached. But you can do this;

```javascript
await tag('my-tag', false);

// value is false
console.log(await Homey.flowToken.getFlowToken({
  uri: 'homey:app:com.athom.homeyscript',
  id: 'my-tag'
}));

await tag('my-tag', true);

// value is false (cached)
console.log(await Homey.flowToken.getFlowToken({
  uri: 'homey:app:com.athom.homeyscript',
  id: 'my-tag'
}));

// value is true (skipped cache)
console.log(await Homey.flowToken.getFlowToken({
  $skipCache: true,
  uri: 'homey:app:com.athom.homeyscript',
  id: 'my-tag'
}));
```

Notice the last call with `$skipCache`.

What's the use case here? Persisting tag values across multiple script executions or using it multiple times in the same script?

**Comment by BOverdevest** [comment] 2021-04-03 07:11
Use case would be across scripts. So the

**Comment by jeroenwienk** [comment] 2021-04-03 11:11
> Two questions
> 
> 1. I posted a similar question on the homey forum, and copied your comprehensive answer there as well. I hope this is ok?
> 2. it would be handy if this functionality was available strAight in the 'tag' method/function. I do see that the udi is needed, but maybe the scope could be restricted to 'homeyscript' only? Or have that one as default?

1. Ofcourse!
2. The problem is that we currently can't change it to your `a = await tag("my-tag")` proposal. This would break scripts for people already using `await tag("my-tag")` since calling it with `null` or `undefined`(the case here) would delete the token.

So the only option I see is to add a new method `getTagValue` to read the value which throws when the tag is not found. Or just use the `Homey.flowToken.getFlowToken`  in your script if you need to read it. Thoughts @WeeJeWel ?

**Comment by WeeJeWel** [comment] 2021-04-03 11:39
Well, tags are only setable from the Apps SDK so reading them would be a hack either way.

Personally I think you should simply use the global storage and sync to a tag.

**Comment by jeroenwienk** [comment] 2021-04-09 09:22
Closing this in favor of syncing the global tag state yourself with `global.set(String key, Mixed value)` before each tag call. Or the other option, fetching it via the API.

**Closed by jeroenwienk** 2021-04-09 09:22 UTC
